name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Hugo
        run: |
          HUGO_VERSION="0.92.1" # Replace with the desired Hugo version
          wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"
          tar -xzvf "hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"
          sudo mv hugo /usr/local/bin/hugo
          rm "hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"

      - name: Install dependencies
        run: |
          npm install -g postcss postcss-cli autoprefixer
          npm install

      - name: Build Hugo site
        run: |
          hugo

      - name: Run PostCSS
        run: |
          postcss src/scss/main.scss -o static/css/main.css --use autoprefixer

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
